/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quasisTest;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Wei Wang
 */
public class FoodAllergy84 extends QuasisTest {

    public FoodAllergy84() {
        super();
        this.oldPanelIndex2NewPanelIndexMap = new HashMap();
        
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 8 , x -> new ArrayList()).add(29);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 9 , x -> new ArrayList()).add(75);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 12 , x -> new ArrayList()).add(94);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 16 , x -> new ArrayList()).add(65);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 16 , x -> new ArrayList()).add(76);
        
        this.testName = "FAAE_84";
        this.testType = "Food_Allergy_84";
        
        this.unitDataTable = "tsp_test_unit_data.faae_unit_data";
        this.dataTable = "`vibrant_test_raw_data`.`food_allergy_84`";
        this.negativeLocation = "D6";
        this.indexTestTitleArr = new String[]{
            "BROWN_RICE_IGE",
            "SCALLOPS_IGE",
            "SESAME_IGE",
            "VANILLA_BEAN_IGE",
            "BLACK_WALNU_IGE",
            "OATS_IGE",
            "WATERMEL_IGE",
            "TOMATO_IGE",
            "CASOMORP_IGE",
            "BLACKBER_IGE",
            "WHITE_POTAT_IGE",
            "ROSEMARY_IGE",
            "SQUASH_IGE",
            "SPINACH_IGE",
            "TURKEY_IGE",
            "SALMON_IGE",
            "RASPBERR_IGE",
            "SEAWEED(_IGE",
            "PEACH_IGE",
            "PEAR_IGE",
            "PECAN_IGE",
            "BLACK_PEPPE_IGE",
            "PERCH_IGE",
            "BETA_CAS_IGE",
            "SWEET_POTAT_IGE",
            "AVOCADO_IGE",
            "AMARANTH_IGE",
            "PORK_IGE",
            "MALT_IGE",
            "KIDNEY_BEAN_IGE",
            "MUSHROOM_IGE",
            "NUTMEG_IGE",
            "OLIVE_IGE",
            "MUSTARD_IGE",
            "NAVY_BEAN_IGE",
            "ONION_IGE",
            "ORANGE_IGE",
            "GREEN_PEAS_IGE",
            "GREEN_PEPPE_IGE",
            "LETTUCE_IGE",
            "LOBSTER_IGE",
            "MACKEREL_IGE",
            "GRAPEFRU_IGE",
            "HALIBUT_IGE",
            "LAKE_TROUT_IGE",
            "HOPS_IGE",
            "CINNAMON_IGE",
            "CLAM_IGE",
            "COFFEE_IGE",
            "GARLIC_IGE",
            "GRAPE_IGE",
            "CODFISH_IGE",
            "GINGER_IGE",
            "CUCUMBER_IGE",
            "CARROT_IGE",
            "BLUEBERR_IGE",
            "CASHEWS_IGE",
            "GREEN_BEAN_IGE",
            "CANTALOU_IGE",
            "CAULIFLO_IGE",
            "APPLE_IGE",
            "BEEF_IGE",
            "CATFISH_IGE",
            "STRAWBER_IGE",
            "CELERY_IGE",
            "CHERRY_IGE",
            "YEAST_IGE",
            "WHEY_PROTE_IGE",
            "LIMA_BEAN_IGE",
            "COCONUT_IGE",
            "APRICOT_IGE",
            "CABBAGE_IGE",
            "LAMB_IGE",
            "BUCKWHEA_IGE",
            "BROCCOLI_IGE",
            "CHICKEN_IGE",
            "ALMOND_IGE",
            "BANANA_IGE",
            "BARLEY_IGE",
            "COCOA_IGE",
            "CRANBERR_IGE",
            "GOATS_MILK_IGE",
            "PINEAPPL_IGE",
            "RYE_IGE"};

        this.indexTestMapArr = new String[]{"Positive control",
            "BROWN_RICE_IGE",
            "SCALLOPS_IGE",
            "SESAME_IGE",
            "VANILLA_BEAN_IGE",
            "BLACK_WALNU_IGE",
            "OATS_IGE",
            "WATERMEL_IGE",
            "TOMATO_IGE",
            "Positive control",
            "CASOMORP_IGE",
            "BLACKBER_IGE",
            "WHITE_POTAT_IGE",
            "ROSEMARY_IGE",
            "SQUASH_IGE",
            "SPINACH_IGE",
            "TURKEY_IGE",
            "SALMON_IGE",
            "RASPBERR_IGE",
            "SEAWEED(_IGE",
            "PEACH_IGE",
            "PEAR_IGE",
            "PECAN_IGE",
            "BLACK_PEPPE_IGE",
            "PERCH_IGE",
            "BETA_CAS_IGE",
            "SWEET_POTAT_IGE",
            "AVOCADO_IGE",
            "AMARANTH_IGE",
            "PORK_IGE",
            "MALT_IGE",
            "KIDNEY_BEAN_IGE",
            "MUSHROOM_IGE",
            "NUTMEG_IGE",
            "OLIVE_IGE",
            "MUSTARD_IGE",
            "NAVY_BEAN_IGE",
            "ONION_IGE",
            "ORANGE_IGE",
            "GREEN_PEAS_IGE",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "GREEN_PEPPE_IGE",
            "LETTUCE_IGE",
            "LOBSTER_IGE",
            "MACKEREL_IGE",
            "GRAPEFRU_IGE",
            "HALIBUT_IGE",
            "LAKE_TROUT_IGE",
            "HOPS_IGE",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "CINNAMON_IGE",
            "CLAM_IGE",
            "COFFEE_IGE",
            "GARLIC_IGE",
            "GRAPE_IGE",
            "CODFISH_IGE",
            "GINGER_IGE",
            "CUCUMBER_IGE",
            "CARROT_IGE",
            "BLUEBERR_IGE",
            "CASHEWS_IGE",
            "GREEN_BEAN_IGE",
            "CANTALOU_IGE",
            "CAULIFLO_IGE",
            "APPLE_IGE",
            "BEEF_IGE",
            "CATFISH_IGE",
            "STRAWBER_IGE",
            "CELERY_IGE",
            "CHERRY_IGE",
            "YEAST_IGE",
            "WHEY_PROTE_IGE",
            "LIMA_BEAN_IGE",
            "COCONUT_IGE",
            "APRICOT_IGE",
            "CABBAGE_IGE",
            "LAMB_IGE",
            "BUCKWHEA_IGE",
            "BROCCOLI_IGE",
            "CHICKEN_IGE",
            "Positive control",
            "ALMOND_IGE",
            "BANANA_IGE",
            "BARLEY_IGE",
            "COCOA_IGE",
            "CRANBERR_IGE",
            "GOATS_MILK_IGE",
            "PINEAPPL_IGE",
            "RYE_IGE",
            "Positive control"
        };

        this.indexTestEquationOffset = new float[][]{
        {-1, -1},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {-1, -1},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {-1, -1},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {0, 0},
        {-1, -1}};



        this.indexTestUnitThreshold = new float[][]{{-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1}};



        this.caliIndexMap.put("B6", 14);
        this.caliIndexMap.put("C6", 14);
        this.caliIndexMap.put("D6", 14);
        this.YStandard = new float[]{10f, 20f, 100f};

    }
}
