/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quasisTest;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author Wei Wang
 */
public class Upre extends QuasisTest {

    public Upre() {
        super();
        
        
        this.oldPanelIndex2NewPanelIndexMap = new HashMap();
        
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 4 , x -> new ArrayList()).add(96);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 5 , x -> new ArrayList()).add(84);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 7 , x -> new ArrayList()).add(74);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 7 , x -> new ArrayList()).add(87);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 7 , x -> new ArrayList()).add(91);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 8 , x -> new ArrayList()).add(88);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 9 , x -> new ArrayList()).add(72);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 10 , x -> new ArrayList()).add(80);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 13 , x -> new ArrayList()).add(83);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 14 , x -> new ArrayList()).add(87);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 15 , x -> new ArrayList()).add(12);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 16 , x -> new ArrayList()).add(86);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 17 , x -> new ArrayList()).add(2);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 17 , x -> new ArrayList()).add(3);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 17 , x -> new ArrayList()).add(4);
        this.oldPanelIndex2NewPanelIndexMap.computeIfAbsent( 19 , x -> new ArrayList()).add(19);
        
        this.testName = "UPRE";
        this.testType = "UPRE";
        
        this.unitDataTable = "tsp_test_unit_data.upre_unit_data";
        this.dataTable = "`vibrant_test_raw_data`.`inhalant_test`";
        this.negativeLocation = "D6";
        this.indexTestTitleArr = new String[]{
            "PHOMA_BETAE",
            "DERMATOPHAGOIDES_FARINAE",
            "DERMATOPHAGOIDES_PTERONYSSINUS",
            "MITE_MIX",
            "RED_ALDER",
            "MUCOR_RACEMOSUS",
            "FUSARIUM_MONILIFORME",
            "Calibrator",
            "TIMOTHY",
            "CANDIDA_ALBICANS",
            "CAT_EPITHELIA",
            "AUSTRALIAN_PINE",
            "RED_MULBERRY",
            "PECAN",
            "ASH_MIX",
            "SHEEP_SORREL",
            "TRICHODERMA_HARZIANUM",
            "ALTERNARIA_ALTERNATA",
            "ACACIA",
            "BLOMIA_TROPICALIS",
            "BOX_ELDER_IP",
            "RAGWEED__SHORT",
            "WHITE_BIRCH",
            "BAHIA_GRASS",
            "NETTLE",
            "COCKROACH",
            "ASPERGILLUS_FUMIGATUS",
            "BLACK_WALNUT",
            "HELMINTHOSPORIUM_SOLANI",
            "MUGWORT",
            "EPICOCCUM_NIGRUM",
            "PENICILLIUM_CHRYSOGENUM",
            "KENTUCKY_BLUE_JUNE",
            "AMERICAN_ELM",
            "WHITE_OAK",
            "DOG_EPITHELIA",
            "JOHNSON_GRASS",
            "REDTOP",
            "RUSSIAN_THISTLE",
            "PERENNIAL_RYEGRASS",
            "MOUNTAIN_CEDAR",
            "CLADOSPORIUM_HERBARUM",
            "AMERICAN_SYCAMORE",
            "BERMUDA",
            "BLACK_OAK",
            "RHIZOPUS_STOLONIFER",
            "PIGWEED"
        };

        this.indexTestMapArr = new String[]{"Positive control",
            "PHOMA_BETAE",
            "DERMATOPHAGOIDES_FARINAE",
            "DERMATOPHAGOIDES_PTERONYSSINUS",
            "MITE_MIX",
            "RED_ALDER",
            "MUCOR_RACEMOSUS",
            "FUSARIUM_MONILIFORME",
            "Calibrator",
            "Positive control",
            "TIMOTHY",
            "CANDIDA_ALBICANS",
            "CAT_EPITHELIA",
            "AUSTRALIAN_PINE",
            "RED_MULBERRY",
            "PECAN",
            "ASH_MIX",
            "SHEEP_SORREL",
            "TRICHODERMA_HARZIANUM",
            "ALTERNARIA_ALTERNATA",
            "ACACIA",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "Positive control",
            "BLOMIA_TROPICALIS",
            "BOX_ELDER_IP",
            "RAGWEED__SHORT",
            "WHITE_BIRCH",
            "BAHIA_GRASS",
            "NETTLE",
            "COCKROACH",
            "ASPERGILLUS_FUMIGATUS",
            "BLACK_WALNUT",
            "HELMINTHOSPORIUM_SOLANI",
            "MUGWORT",
            "EPICOCCUM_NIGRUM",
            "PENICILLIUM_CHRYSOGENUM",
            "KENTUCKY_BLUE_JUNE",
            "AMERICAN_ELM",
            "WHITE_OAK",
            "DOG_EPITHELIA",
            "JOHNSON_GRASS",
            "REDTOP",
            "RUSSIAN_THISTLE",
            "Positive control",
            "PERENNIAL_RYEGRASS",
            "MOUNTAIN_CEDAR",
            "CLADOSPORIUM_HERBARUM",
            "AMERICAN_SYCAMORE",
            "BERMUDA",
            "BLACK_OAK",
            "RHIZOPUS_STOLONIFER",
            "PIGWEED",
            "Positive control"

        };

        this.indexTestEquationOffset = new float[][]{
            {-1, -1},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {-1, -1},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {-1, -1},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {-1, -1},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {0, 0},
            {-1, -1}};

        this.indexTestUnitThreshold = new float[][]{{-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {0.29f, 100},
        {-1, -1}};

        this.caliIndexMap.put("B6", 14);
        this.caliIndexMap.put("C6", 14);
        this.caliIndexMap.put("D6", 14);
        this.YStandard = new float[]{10f, 20f, 100f};

    }
}
